server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
     
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    async:
      request-timeout: 500000
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chzapp?serverTimezone=Asia/Seoul
    username: chz
    password: chz93

    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     # use-new-id-generator-mappings: false
    # show-sql: true
    properties:
      "[hibernate.format_sql]": true

  jackson:
    serialization:
      fail-on-empty-beans: false
    date-format: "yyyy-MM-dd HH:mm"
      
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true
      location: D:/WorkSpace/Temp
         
